// Package quotes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/faetools/devtool version (devel) DO NOT EDIT.
package quotes

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

const (
	HapikeyScopes = "hapikey.Scopes"
)

// Defines values for BatchResponseSimplePublicObjectStatus.
const (
	BatchResponseSimplePublicObjectStatusCANCELED BatchResponseSimplePublicObjectStatus = "CANCELED"

	BatchResponseSimplePublicObjectStatusCOMPLETE BatchResponseSimplePublicObjectStatus = "COMPLETE"

	BatchResponseSimplePublicObjectStatusPENDING BatchResponseSimplePublicObjectStatus = "PENDING"

	BatchResponseSimplePublicObjectStatusPROCESSING BatchResponseSimplePublicObjectStatus = "PROCESSING"
)

// Defines values for BatchResponseSimplePublicObjectWithErrorsStatus.
const (
	BatchResponseSimplePublicObjectWithErrorsStatusCANCELED BatchResponseSimplePublicObjectWithErrorsStatus = "CANCELED"

	BatchResponseSimplePublicObjectWithErrorsStatusCOMPLETE BatchResponseSimplePublicObjectWithErrorsStatus = "COMPLETE"

	BatchResponseSimplePublicObjectWithErrorsStatusPENDING BatchResponseSimplePublicObjectWithErrorsStatus = "PENDING"

	BatchResponseSimplePublicObjectWithErrorsStatusPROCESSING BatchResponseSimplePublicObjectWithErrorsStatus = "PROCESSING"
)

// Defines values for ErrorCategoryHttpStatus.
const (
	ErrorCategoryHttpStatusACCEPTED ErrorCategoryHttpStatus = "ACCEPTED"

	ErrorCategoryHttpStatusALREADYREPORTED ErrorCategoryHttpStatus = "ALREADY_REPORTED"

	ErrorCategoryHttpStatusBADGATEWAY ErrorCategoryHttpStatus = "BAD_GATEWAY"

	ErrorCategoryHttpStatusBADREQUEST ErrorCategoryHttpStatus = "BAD_REQUEST"

	ErrorCategoryHttpStatusCONFLICT ErrorCategoryHttpStatus = "CONFLICT"

	ErrorCategoryHttpStatusCONTINUE ErrorCategoryHttpStatus = "CONTINUE"

	ErrorCategoryHttpStatusCREATED ErrorCategoryHttpStatus = "CREATED"

	ErrorCategoryHttpStatusEXPECTATIONFAILED ErrorCategoryHttpStatus = "EXPECTATION_FAILED"

	ErrorCategoryHttpStatusFAILEDDEPENDENCY ErrorCategoryHttpStatus = "FAILED_DEPENDENCY"

	ErrorCategoryHttpStatusFORBIDDEN ErrorCategoryHttpStatus = "FORBIDDEN"

	ErrorCategoryHttpStatusFOUND ErrorCategoryHttpStatus = "FOUND"

	ErrorCategoryHttpStatusGATEWAYTIMEOUT ErrorCategoryHttpStatus = "GATEWAY_TIMEOUT"

	ErrorCategoryHttpStatusGONE ErrorCategoryHttpStatus = "GONE"

	ErrorCategoryHttpStatusHTTPVERSIONNOTSUPPORTED ErrorCategoryHttpStatus = "HTTP_VERSION_NOT_SUPPORTED"

	ErrorCategoryHttpStatusIMATEAPOT ErrorCategoryHttpStatus = "IM_A_TEAPOT"

	ErrorCategoryHttpStatusIMUSED ErrorCategoryHttpStatus = "IM_USED"

	ErrorCategoryHttpStatusINSUFFICIENTSTORAGE ErrorCategoryHttpStatus = "INSUFFICIENT_STORAGE"

	ErrorCategoryHttpStatusINTERNALSERVERERROR ErrorCategoryHttpStatus = "INTERNAL_SERVER_ERROR"

	ErrorCategoryHttpStatusINTERNALSTALESERVICEDISCOVERY ErrorCategoryHttpStatus = "INTERNAL_STALE_SERVICE_DISCOVERY"

	ErrorCategoryHttpStatusLENGTHREQUIRED ErrorCategoryHttpStatus = "LENGTH_REQUIRED"

	ErrorCategoryHttpStatusLOCKED ErrorCategoryHttpStatus = "LOCKED"

	ErrorCategoryHttpStatusLOOPDETECTED ErrorCategoryHttpStatus = "LOOP_DETECTED"

	ErrorCategoryHttpStatusMETHODNOTALLOWED ErrorCategoryHttpStatus = "METHOD_NOT_ALLOWED"

	ErrorCategoryHttpStatusMISDIRECTEDREQUEST ErrorCategoryHttpStatus = "MISDIRECTED_REQUEST"

	ErrorCategoryHttpStatusMOVEDPERMANENTLY ErrorCategoryHttpStatus = "MOVED_PERMANENTLY"

	ErrorCategoryHttpStatusMULTIPLECHOICES ErrorCategoryHttpStatus = "MULTIPLE_CHOICES"

	ErrorCategoryHttpStatusMULTISTATUS ErrorCategoryHttpStatus = "MULTI_STATUS"

	ErrorCategoryHttpStatusNETWORKAUTHENTICATIONREQUIRED ErrorCategoryHttpStatus = "NETWORK_AUTHENTICATION_REQUIRED"

	ErrorCategoryHttpStatusNOCONTENT ErrorCategoryHttpStatus = "NO_CONTENT"

	ErrorCategoryHttpStatusNONAUTHORITATIVEINFORMATION ErrorCategoryHttpStatus = "NON_AUTHORITATIVE_INFORMATION"

	ErrorCategoryHttpStatusNOTACCEPTABLE ErrorCategoryHttpStatus = "NOT_ACCEPTABLE"

	ErrorCategoryHttpStatusNOTEXTENDED ErrorCategoryHttpStatus = "NOT_EXTENDED"

	ErrorCategoryHttpStatusNOTFOUND ErrorCategoryHttpStatus = "NOT_FOUND"

	ErrorCategoryHttpStatusNOTIMPLEMENTED ErrorCategoryHttpStatus = "NOT_IMPLEMENTED"

	ErrorCategoryHttpStatusNOTMODIFIED ErrorCategoryHttpStatus = "NOT_MODIFIED"

	ErrorCategoryHttpStatusOK ErrorCategoryHttpStatus = "OK"

	ErrorCategoryHttpStatusPARTIALCONTENT ErrorCategoryHttpStatus = "PARTIAL_CONTENT"

	ErrorCategoryHttpStatusPAYMENTREQUIRED ErrorCategoryHttpStatus = "PAYMENT_REQUIRED"

	ErrorCategoryHttpStatusPERMANENTREDIRECT ErrorCategoryHttpStatus = "PERMANENT_REDIRECT"

	ErrorCategoryHttpStatusPRECONDITIONFAILED ErrorCategoryHttpStatus = "PRECONDITION_FAILED"

	ErrorCategoryHttpStatusPRECONDITIONREQUIRED ErrorCategoryHttpStatus = "PRECONDITION_REQUIRED"

	ErrorCategoryHttpStatusPROCESSING ErrorCategoryHttpStatus = "PROCESSING"

	ErrorCategoryHttpStatusPROXYAUTHENTICATIONREQUIRED ErrorCategoryHttpStatus = "PROXY_AUTHENTICATION_REQUIRED"

	ErrorCategoryHttpStatusREQUESTEDRANGENOTSATISFIABLE ErrorCategoryHttpStatus = "REQUESTED_RANGE_NOT_SATISFIABLE"

	ErrorCategoryHttpStatusREQUESTENTITYTOOLARGE ErrorCategoryHttpStatus = "REQUEST_ENTITY_TOO_LARGE"

	ErrorCategoryHttpStatusREQUESTHEADERSFIELDSTOOLARGE ErrorCategoryHttpStatus = "REQUEST_HEADERS_FIELDS_TOO_LARGE"

	ErrorCategoryHttpStatusREQUESTTIMEOUT ErrorCategoryHttpStatus = "REQUEST_TIMEOUT"

	ErrorCategoryHttpStatusREQUESTURITOOLONG ErrorCategoryHttpStatus = "REQUEST_URI_TOO_LONG"

	ErrorCategoryHttpStatusRESETCONTENT ErrorCategoryHttpStatus = "RESET_CONTENT"

	ErrorCategoryHttpStatusSEEOTHER ErrorCategoryHttpStatus = "SEE_OTHER"

	ErrorCategoryHttpStatusSERVICEUNAVAILABLE ErrorCategoryHttpStatus = "SERVICE_UNAVAILABLE"

	ErrorCategoryHttpStatusSWITCHINGPROTOCOLS ErrorCategoryHttpStatus = "SWITCHING_PROTOCOLS"

	ErrorCategoryHttpStatusTEMPORARYREDIRECT ErrorCategoryHttpStatus = "TEMPORARY_REDIRECT"

	ErrorCategoryHttpStatusTOOMANYREQUESTS ErrorCategoryHttpStatus = "TOO_MANY_REQUESTS"

	ErrorCategoryHttpStatusUNAUTHORIZED ErrorCategoryHttpStatus = "UNAUTHORIZED"

	ErrorCategoryHttpStatusUNAVAILABLEFORLEGALREASONS ErrorCategoryHttpStatus = "UNAVAILABLE_FOR_LEGAL_REASONS"

	ErrorCategoryHttpStatusUNPROCESSABLEENTITY ErrorCategoryHttpStatus = "UNPROCESSABLE_ENTITY"

	ErrorCategoryHttpStatusUNSUPPORTEDMEDIATYPE ErrorCategoryHttpStatus = "UNSUPPORTED_MEDIA_TYPE"

	ErrorCategoryHttpStatusUPGRADEREQUIRED ErrorCategoryHttpStatus = "UPGRADE_REQUIRED"

	ErrorCategoryHttpStatusUSEPROXY ErrorCategoryHttpStatus = "USE_PROXY"

	ErrorCategoryHttpStatusVARIANTALSONEGOTIATES ErrorCategoryHttpStatus = "VARIANT_ALSO_NEGOTIATES"
)

// Defines values for FilterOperator.
const (
	FilterOperatorBETWEEN FilterOperator = "BETWEEN"

	FilterOperatorCONTAINSTOKEN FilterOperator = "CONTAINS_TOKEN"

	FilterOperatorEQ FilterOperator = "EQ"

	FilterOperatorGT FilterOperator = "GT"

	FilterOperatorGTE FilterOperator = "GTE"

	FilterOperatorHASPROPERTY FilterOperator = "HAS_PROPERTY"

	FilterOperatorIN FilterOperator = "IN"

	FilterOperatorLT FilterOperator = "LT"

	FilterOperatorLTE FilterOperator = "LTE"

	FilterOperatorNEQ FilterOperator = "NEQ"

	FilterOperatorNOTCONTAINSTOKEN FilterOperator = "NOT_CONTAINS_TOKEN"

	FilterOperatorNOTHASPROPERTY FilterOperator = "NOT_HAS_PROPERTY"

	FilterOperatorNOTIN FilterOperator = "NOT_IN"
)

// AssociatedId defines model for AssociatedId.
type AssociatedId struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// BatchReadInputSimplePublicObjectId defines model for BatchReadInputSimplePublicObjectId.
type BatchReadInputSimplePublicObjectId struct {
	IdProperty *string                `json:"idProperty,omitempty"`
	Inputs     []SimplePublicObjectId `json:"inputs"`
	Properties []string               `json:"properties"`
}

// BatchResponseSimplePublicObject defines model for BatchResponseSimplePublicObject.
type BatchResponseSimplePublicObject struct {
	CompletedAt time.Time                              `json:"completedAt"`
	Links       *BatchResponseSimplePublicObject_Links `json:"links,omitempty"`
	RequestedAt *time.Time                             `json:"requestedAt,omitempty"`
	Results     []SimplePublicObject                   `json:"results"`
	StartedAt   time.Time                              `json:"startedAt"`
	Status      BatchResponseSimplePublicObjectStatus  `json:"status"`
}

// BatchResponseSimplePublicObject_Links defines model for BatchResponseSimplePublicObject.Links.
type BatchResponseSimplePublicObject_Links struct {
	AdditionalProperties map[string]string `json:"-"`
}

// BatchResponseSimplePublicObjectStatus defines model for BatchResponseSimplePublicObject.Status.
type BatchResponseSimplePublicObjectStatus string

// BatchResponseSimplePublicObjectWithErrors defines model for BatchResponseSimplePublicObjectWithErrors.
type BatchResponseSimplePublicObjectWithErrors struct {
	CompletedAt time.Time                                        `json:"completedAt"`
	Errors      *[]StandardError                                 `json:"errors,omitempty"`
	Links       *BatchResponseSimplePublicObjectWithErrors_Links `json:"links,omitempty"`
	NumErrors   *int32                                           `json:"numErrors,omitempty"`
	RequestedAt *time.Time                                       `json:"requestedAt,omitempty"`
	Results     []SimplePublicObject                             `json:"results"`
	StartedAt   time.Time                                        `json:"startedAt"`
	Status      BatchResponseSimplePublicObjectWithErrorsStatus  `json:"status"`
}

// BatchResponseSimplePublicObjectWithErrors_Links defines model for BatchResponseSimplePublicObjectWithErrors.Links.
type BatchResponseSimplePublicObjectWithErrors_Links struct {
	AdditionalProperties map[string]string `json:"-"`
}

// BatchResponseSimplePublicObjectWithErrorsStatus defines model for BatchResponseSimplePublicObjectWithErrors.Status.
type BatchResponseSimplePublicObjectWithErrorsStatus string

// CollectionResponseAssociatedId defines model for CollectionResponseAssociatedId.
type CollectionResponseAssociatedId struct {
	Paging  *Paging        `json:"paging,omitempty"`
	Results []AssociatedId `json:"results"`
}

// CollectionResponseAssociatedIdForwardPaging defines model for CollectionResponseAssociatedIdForwardPaging.
type CollectionResponseAssociatedIdForwardPaging struct {
	Paging  *ForwardPaging `json:"paging,omitempty"`
	Results []AssociatedId `json:"results"`
}

// CollectionResponseSimplePublicObjectWithAssociationsForwardPaging defines model for CollectionResponseSimplePublicObjectWithAssociationsForwardPaging.
type CollectionResponseSimplePublicObjectWithAssociationsForwardPaging struct {
	Paging  *ForwardPaging                       `json:"paging,omitempty"`
	Results []SimplePublicObjectWithAssociations `json:"results"`
}

// CollectionResponseWithTotalSimplePublicObjectForwardPaging defines model for CollectionResponseWithTotalSimplePublicObjectForwardPaging.
type CollectionResponseWithTotalSimplePublicObjectForwardPaging struct {
	Paging  *ForwardPaging       `json:"paging,omitempty"`
	Results []SimplePublicObject `json:"results"`
	Total   int32                `json:"total"`
}

// Error defines model for Error.
type Error struct {
	// The error category
	Category string `json:"category"`

	// Context about the error condition
	Context *Error_Context `json:"context,omitempty"`

	// A unique identifier for the request. Include this value with any error reports or support tickets
	CorrelationId string `json:"correlationId"`

	// further information about the error
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// A map of link names to associated URIs containing documentation about the error or recommended remediation steps
	Links *Error_Links `json:"links,omitempty"`

	// A human readable message describing the error along with remediation steps where appropriate
	Message string `json:"message"`

	// A specific category that contains more specific detail about the error
	SubCategory *string `json:"subCategory,omitempty"`
}

// Context about the error condition
type Error_Context struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// A map of link names to associated URIs containing documentation about the error or recommended remediation steps
type Error_Links struct {
	AdditionalProperties map[string]string `json:"-"`
}

// ErrorCategory defines model for ErrorCategory.
type ErrorCategory struct {
	HttpStatus ErrorCategoryHttpStatus `json:"httpStatus"`
	Name       string                  `json:"name"`
}

// ErrorCategoryHttpStatus defines model for ErrorCategory.HttpStatus.
type ErrorCategoryHttpStatus string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// The status code associated with the error detail
	Code *string `json:"code,omitempty"`

	// Context about the error condition
	Context *ErrorDetail_Context `json:"context,omitempty"`

	// The name of the field or parameter in which the error was found.
	In *string `json:"in,omitempty"`

	// A human readable message describing the error along with remediation steps where appropriate
	Message string `json:"message"`

	// A specific category that contains more specific detail about the error
	SubCategory *string `json:"subCategory,omitempty"`
}

// Context about the error condition
type ErrorDetail_Context struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// Filter defines model for Filter.
type Filter struct {
	// null
	Operator     FilterOperator `json:"operator"`
	PropertyName string         `json:"propertyName"`
	Value        *string        `json:"value,omitempty"`
}

// null
type FilterOperator string

// FilterGroup defines model for FilterGroup.
type FilterGroup struct {
	Filters []Filter `json:"filters"`
}

// ForwardPaging defines model for ForwardPaging.
type ForwardPaging struct {
	Next *NextPage `json:"next,omitempty"`
}

// NextPage defines model for NextPage.
type NextPage struct {
	After string  `json:"after"`
	Link  *string `json:"link,omitempty"`
}

// Paging defines model for Paging.
type Paging struct {
	Next *NextPage     `json:"next,omitempty"`
	Prev *PreviousPage `json:"prev,omitempty"`
}

// PreviousPage defines model for PreviousPage.
type PreviousPage struct {
	Before string  `json:"before"`
	Link   *string `json:"link,omitempty"`
}

// PublicObjectSearchRequest defines model for PublicObjectSearchRequest.
type PublicObjectSearchRequest struct {
	After        int32         `json:"after"`
	FilterGroups []FilterGroup `json:"filterGroups"`
	Limit        int32         `json:"limit"`
	Properties   []string      `json:"properties"`
	Query        *string       `json:"query,omitempty"`
	Sorts        []string      `json:"sorts"`
}

// SimplePublicObject defines model for SimplePublicObject.
type SimplePublicObject struct {
	Archived   *bool                         `json:"archived,omitempty"`
	ArchivedAt *time.Time                    `json:"archivedAt,omitempty"`
	CreatedAt  time.Time                     `json:"createdAt"`
	Id         string                        `json:"id"`
	Properties SimplePublicObject_Properties `json:"properties"`
	UpdatedAt  time.Time                     `json:"updatedAt"`
}

// SimplePublicObject_Properties defines model for SimplePublicObject.Properties.
type SimplePublicObject_Properties struct {
	AdditionalProperties map[string]string `json:"-"`
}

// SimplePublicObjectId defines model for SimplePublicObjectId.
type SimplePublicObjectId struct {
	Id string `json:"id"`
}

// SimplePublicObjectWithAssociations defines model for SimplePublicObjectWithAssociations.
type SimplePublicObjectWithAssociations struct {
	Archived     *bool                                            `json:"archived,omitempty"`
	ArchivedAt   *time.Time                                       `json:"archivedAt,omitempty"`
	Associations *SimplePublicObjectWithAssociations_Associations `json:"associations,omitempty"`
	CreatedAt    time.Time                                        `json:"createdAt"`
	Id           string                                           `json:"id"`
	Properties   SimplePublicObjectWithAssociations_Properties    `json:"properties"`
	UpdatedAt    time.Time                                        `json:"updatedAt"`
}

// SimplePublicObjectWithAssociations_Associations defines model for SimplePublicObjectWithAssociations.Associations.
type SimplePublicObjectWithAssociations_Associations struct {
	AdditionalProperties map[string]CollectionResponseAssociatedId `json:"-"`
}

// SimplePublicObjectWithAssociations_Properties defines model for SimplePublicObjectWithAssociations.Properties.
type SimplePublicObjectWithAssociations_Properties struct {
	AdditionalProperties map[string]string `json:"-"`
}

// StandardError defines model for StandardError.
type StandardError struct {
	Category    ErrorCategory           `json:"category"`
	Context     StandardError_Context   `json:"context"`
	Errors      []ErrorDetail           `json:"errors"`
	Id          *string                 `json:"id,omitempty"`
	Links       StandardError_Links     `json:"links"`
	Message     string                  `json:"message"`
	Status      string                  `json:"status"`
	SubCategory *map[string]interface{} `json:"subCategory,omitempty"`
}

// StandardError_Context defines model for StandardError.Context.
type StandardError_Context struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// StandardError_Links defines model for StandardError.Links.
type StandardError_Links struct {
	AdditionalProperties map[string]string `json:"-"`
}

// Getcrmv3objectsquotesGetPageParams defines parameters for Getcrmv3objectsquotesGetPage.
type Getcrmv3objectsquotesGetPageParams struct {
	// The maximum number of results to display per page.
	Limit *int32 `json:"limit,omitempty"`

	// The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.
	After *string `json:"after,omitempty"`

	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties *[]string `json:"properties,omitempty"`

	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations *[]string `json:"associations,omitempty"`

	// Whether to return only results that have been archived.
	Archived *bool `json:"archived,omitempty"`
}

// Postcrmv3objectsquotesbatchreadReadJSONBody defines parameters for Postcrmv3objectsquotesbatchreadRead.
type Postcrmv3objectsquotesbatchreadReadJSONBody BatchReadInputSimplePublicObjectId

// Postcrmv3objectsquotesbatchreadReadParams defines parameters for Postcrmv3objectsquotesbatchreadRead.
type Postcrmv3objectsquotesbatchreadReadParams struct {
	// Whether to return only results that have been archived.
	Archived *bool `json:"archived,omitempty"`
}

// Postcrmv3objectsquotessearchDoSearchJSONBody defines parameters for Postcrmv3objectsquotessearchDoSearch.
type Postcrmv3objectsquotessearchDoSearchJSONBody PublicObjectSearchRequest

// Getcrmv3objectsquotesQuoteIdGetByIdParams defines parameters for Getcrmv3objectsquotesQuoteIdGetById.
type Getcrmv3objectsquotesQuoteIdGetByIdParams struct {
	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties *[]string `json:"properties,omitempty"`

	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations *[]string `json:"associations,omitempty"`

	// Whether to return only results that have been archived.
	Archived *bool `json:"archived,omitempty"`

	// The name of a property whose values are unique for this object type
	IdProperty *string `json:"idProperty,omitempty"`
}

// Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams defines parameters for Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll.
type Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams struct {
	// The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.
	After *string `json:"after,omitempty"`

	// The maximum number of results to display per page.
	Limit *int32 `json:"limit,omitempty"`
}

// Postcrmv3objectsquotesbatchreadReadJSONRequestBody defines body for Postcrmv3objectsquotesbatchreadRead for application/json ContentType.
type Postcrmv3objectsquotesbatchreadReadJSONRequestBody Postcrmv3objectsquotesbatchreadReadJSONBody

// Postcrmv3objectsquotessearchDoSearchJSONRequestBody defines body for Postcrmv3objectsquotessearchDoSearch for application/json ContentType.
type Postcrmv3objectsquotessearchDoSearchJSONRequestBody Postcrmv3objectsquotessearchDoSearchJSONBody

// Getter for additional properties for BatchResponseSimplePublicObject_Links. Returns the specified
// element and whether it was found
func (a BatchResponseSimplePublicObject_Links) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for BatchResponseSimplePublicObject_Links
func (a *BatchResponseSimplePublicObject_Links) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for BatchResponseSimplePublicObject_Links to handle AdditionalProperties
func (a *BatchResponseSimplePublicObject_Links) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for BatchResponseSimplePublicObject_Links to handle AdditionalProperties
func (a BatchResponseSimplePublicObject_Links) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for BatchResponseSimplePublicObjectWithErrors_Links. Returns the specified
// element and whether it was found
func (a BatchResponseSimplePublicObjectWithErrors_Links) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for BatchResponseSimplePublicObjectWithErrors_Links
func (a *BatchResponseSimplePublicObjectWithErrors_Links) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for BatchResponseSimplePublicObjectWithErrors_Links to handle AdditionalProperties
func (a *BatchResponseSimplePublicObjectWithErrors_Links) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for BatchResponseSimplePublicObjectWithErrors_Links to handle AdditionalProperties
func (a BatchResponseSimplePublicObjectWithErrors_Links) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Error_Context. Returns the specified
// element and whether it was found
func (a Error_Context) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Error_Context
func (a *Error_Context) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Error_Context to handle AdditionalProperties
func (a *Error_Context) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Error_Context to handle AdditionalProperties
func (a Error_Context) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Error_Links. Returns the specified
// element and whether it was found
func (a Error_Links) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Error_Links
func (a *Error_Links) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Error_Links to handle AdditionalProperties
func (a *Error_Links) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Error_Links to handle AdditionalProperties
func (a Error_Links) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ErrorDetail_Context. Returns the specified
// element and whether it was found
func (a ErrorDetail_Context) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorDetail_Context
func (a *ErrorDetail_Context) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorDetail_Context to handle AdditionalProperties
func (a *ErrorDetail_Context) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorDetail_Context to handle AdditionalProperties
func (a ErrorDetail_Context) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SimplePublicObject_Properties. Returns the specified
// element and whether it was found
func (a SimplePublicObject_Properties) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SimplePublicObject_Properties
func (a *SimplePublicObject_Properties) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SimplePublicObject_Properties to handle AdditionalProperties
func (a *SimplePublicObject_Properties) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SimplePublicObject_Properties to handle AdditionalProperties
func (a SimplePublicObject_Properties) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SimplePublicObjectWithAssociations_Associations. Returns the specified
// element and whether it was found
func (a SimplePublicObjectWithAssociations_Associations) Get(fieldName string) (value CollectionResponseAssociatedId, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SimplePublicObjectWithAssociations_Associations
func (a *SimplePublicObjectWithAssociations_Associations) Set(fieldName string, value CollectionResponseAssociatedId) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]CollectionResponseAssociatedId)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SimplePublicObjectWithAssociations_Associations to handle AdditionalProperties
func (a *SimplePublicObjectWithAssociations_Associations) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]CollectionResponseAssociatedId)
		for fieldName, fieldBuf := range object {
			var fieldVal CollectionResponseAssociatedId
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SimplePublicObjectWithAssociations_Associations to handle AdditionalProperties
func (a SimplePublicObjectWithAssociations_Associations) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SimplePublicObjectWithAssociations_Properties. Returns the specified
// element and whether it was found
func (a SimplePublicObjectWithAssociations_Properties) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SimplePublicObjectWithAssociations_Properties
func (a *SimplePublicObjectWithAssociations_Properties) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SimplePublicObjectWithAssociations_Properties to handle AdditionalProperties
func (a *SimplePublicObjectWithAssociations_Properties) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SimplePublicObjectWithAssociations_Properties to handle AdditionalProperties
func (a SimplePublicObjectWithAssociations_Properties) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for StandardError_Context. Returns the specified
// element and whether it was found
func (a StandardError_Context) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StandardError_Context
func (a *StandardError_Context) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StandardError_Context to handle AdditionalProperties
func (a *StandardError_Context) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StandardError_Context to handle AdditionalProperties
func (a StandardError_Context) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for StandardError_Links. Returns the specified
// element and whether it was found
func (a StandardError_Links) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StandardError_Links
func (a *StandardError_Links) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StandardError_Links to handle AdditionalProperties
func (a *StandardError_Links) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StandardError_Links to handle AdditionalProperties
func (a StandardError_Links) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Getcrmv3objectsquotesGetPage request
	Getcrmv3objectsquotesGetPage(ctx context.Context, params *Getcrmv3objectsquotesGetPageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Postcrmv3objectsquotesbatchreadRead request with any body
	Postcrmv3objectsquotesbatchreadReadWithBody(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	Postcrmv3objectsquotesbatchreadRead(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, body Postcrmv3objectsquotesbatchreadReadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Postcrmv3objectsquotessearchDoSearch request with any body
	Postcrmv3objectsquotessearchDoSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	Postcrmv3objectsquotessearchDoSearch(ctx context.Context, body Postcrmv3objectsquotessearchDoSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Getcrmv3objectsquotesQuoteIdGetById request
	Getcrmv3objectsquotesQuoteIdGetById(ctx context.Context, quoteId string, params *Getcrmv3objectsquotesQuoteIdGetByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll request
	Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll(ctx context.Context, quoteId string, toObjectType string, params *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Getcrmv3objectsquotesGetPage(ctx context.Context, params *Getcrmv3objectsquotesGetPageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetcrmv3objectsquotesGetPageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postcrmv3objectsquotesbatchreadReadWithBody(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostcrmv3objectsquotesbatchreadReadRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postcrmv3objectsquotesbatchreadRead(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, body Postcrmv3objectsquotesbatchreadReadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostcrmv3objectsquotesbatchreadReadRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postcrmv3objectsquotessearchDoSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostcrmv3objectsquotessearchDoSearchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postcrmv3objectsquotessearchDoSearch(ctx context.Context, body Postcrmv3objectsquotessearchDoSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostcrmv3objectsquotessearchDoSearchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Getcrmv3objectsquotesQuoteIdGetById(ctx context.Context, quoteId string, params *Getcrmv3objectsquotesQuoteIdGetByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetcrmv3objectsquotesQuoteIdGetByIdRequest(c.Server, quoteId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll(ctx context.Context, quoteId string, toObjectType string, params *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllRequest(c.Server, quoteId, toObjectType, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetcrmv3objectsquotesGetPageRequest generates requests for Getcrmv3objectsquotesGetPage
func NewGetcrmv3objectsquotesGetPageRequest(server string, params *Getcrmv3objectsquotesGetPageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm/v3/objects/quotes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Limit != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.After != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "after", runtime.ParamLocationQuery, *params.After); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Properties != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "properties", runtime.ParamLocationQuery, *params.Properties); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Associations != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "associations", runtime.ParamLocationQuery, *params.Associations); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Archived != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "archived", runtime.ParamLocationQuery, *params.Archived); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostcrmv3objectsquotesbatchreadReadRequest calls the generic Postcrmv3objectsquotesbatchreadRead builder with application/json body
func NewPostcrmv3objectsquotesbatchreadReadRequest(server string, params *Postcrmv3objectsquotesbatchreadReadParams, body Postcrmv3objectsquotesbatchreadReadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostcrmv3objectsquotesbatchreadReadRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostcrmv3objectsquotesbatchreadReadRequestWithBody generates requests for Postcrmv3objectsquotesbatchreadRead with any type of body
func NewPostcrmv3objectsquotesbatchreadReadRequestWithBody(server string, params *Postcrmv3objectsquotesbatchreadReadParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm/v3/objects/quotes/batch/read")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Archived != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "archived", runtime.ParamLocationQuery, *params.Archived); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostcrmv3objectsquotessearchDoSearchRequest calls the generic Postcrmv3objectsquotessearchDoSearch builder with application/json body
func NewPostcrmv3objectsquotessearchDoSearchRequest(server string, body Postcrmv3objectsquotessearchDoSearchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostcrmv3objectsquotessearchDoSearchRequestWithBody(server, "application/json", bodyReader)
}

// NewPostcrmv3objectsquotessearchDoSearchRequestWithBody generates requests for Postcrmv3objectsquotessearchDoSearch with any type of body
func NewPostcrmv3objectsquotessearchDoSearchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm/v3/objects/quotes/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetcrmv3objectsquotesQuoteIdGetByIdRequest generates requests for Getcrmv3objectsquotesQuoteIdGetById
func NewGetcrmv3objectsquotesQuoteIdGetByIdRequest(server string, quoteId string, params *Getcrmv3objectsquotesQuoteIdGetByIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "quoteId", runtime.ParamLocationPath, quoteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm/v3/objects/quotes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Properties != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "properties", runtime.ParamLocationQuery, *params.Properties); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Associations != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "associations", runtime.ParamLocationQuery, *params.Associations); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Archived != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "archived", runtime.ParamLocationQuery, *params.Archived); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.IdProperty != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "idProperty", runtime.ParamLocationQuery, *params.IdProperty); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllRequest generates requests for Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll
func NewGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllRequest(server string, quoteId string, toObjectType string, params *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "quoteId", runtime.ParamLocationPath, quoteId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "toObjectType", runtime.ParamLocationPath, toObjectType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/crm/v3/objects/quotes/%s/associations/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.After != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "after", runtime.ParamLocationQuery, *params.After); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	if params.Limit != nil {
		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// Getcrmv3objectsquotesGetPage request
	Getcrmv3objectsquotesGetPageWithResponse(ctx context.Context, params *Getcrmv3objectsquotesGetPageParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesGetPageResponse, error)

	// Postcrmv3objectsquotesbatchreadRead request with any body
	Postcrmv3objectsquotesbatchreadReadWithBodyWithResponse(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotesbatchreadReadResponse, error)
	Postcrmv3objectsquotesbatchreadReadWithResponse(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, body Postcrmv3objectsquotesbatchreadReadJSONRequestBody, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotesbatchreadReadResponse, error)

	// Postcrmv3objectsquotessearchDoSearch request with any body
	Postcrmv3objectsquotessearchDoSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotessearchDoSearchResponse, error)
	Postcrmv3objectsquotessearchDoSearchWithResponse(ctx context.Context, body Postcrmv3objectsquotessearchDoSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotessearchDoSearchResponse, error)

	// Getcrmv3objectsquotesQuoteIdGetById request
	Getcrmv3objectsquotesQuoteIdGetByIdWithResponse(ctx context.Context, quoteId string, params *Getcrmv3objectsquotesQuoteIdGetByIdParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesQuoteIdGetByIdResponse, error)

	// Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll request
	Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllWithResponse(ctx context.Context, quoteId string, toObjectType string, params *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse, error)
}

type Getcrmv3objectsquotesGetPageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
}

// Status returns HTTPResponse.Status
func (r Getcrmv3objectsquotesGetPageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Getcrmv3objectsquotesGetPageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type Postcrmv3objectsquotesbatchreadReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BatchResponseSimplePublicObject
	JSON207      *BatchResponseSimplePublicObjectWithErrors
}

// Status returns HTTPResponse.Status
func (r Postcrmv3objectsquotesbatchreadReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postcrmv3objectsquotesbatchreadReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type Postcrmv3objectsquotessearchDoSearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CollectionResponseWithTotalSimplePublicObjectForwardPaging
}

// Status returns HTTPResponse.Status
func (r Postcrmv3objectsquotessearchDoSearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postcrmv3objectsquotessearchDoSearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type Getcrmv3objectsquotesQuoteIdGetByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SimplePublicObjectWithAssociations
}

// Status returns HTTPResponse.Status
func (r Getcrmv3objectsquotesQuoteIdGetByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Getcrmv3objectsquotesQuoteIdGetByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CollectionResponseAssociatedIdForwardPaging
}

// Status returns HTTPResponse.Status
func (r Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// Getcrmv3objectsquotesGetPageWithResponse request returning *Getcrmv3objectsquotesGetPageResponse
func (c *ClientWithResponses) Getcrmv3objectsquotesGetPageWithResponse(ctx context.Context, params *Getcrmv3objectsquotesGetPageParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesGetPageResponse, error) {
	rsp, err := c.Getcrmv3objectsquotesGetPage(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetcrmv3objectsquotesGetPageResponse(rsp)
}

// Postcrmv3objectsquotesbatchreadReadWithBodyWithResponse request with arbitrary body returning *Postcrmv3objectsquotesbatchreadReadResponse
func (c *ClientWithResponses) Postcrmv3objectsquotesbatchreadReadWithBodyWithResponse(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotesbatchreadReadResponse, error) {
	rsp, err := c.Postcrmv3objectsquotesbatchreadReadWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostcrmv3objectsquotesbatchreadReadResponse(rsp)
}

func (c *ClientWithResponses) Postcrmv3objectsquotesbatchreadReadWithResponse(ctx context.Context, params *Postcrmv3objectsquotesbatchreadReadParams, body Postcrmv3objectsquotesbatchreadReadJSONRequestBody, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotesbatchreadReadResponse, error) {
	rsp, err := c.Postcrmv3objectsquotesbatchreadRead(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostcrmv3objectsquotesbatchreadReadResponse(rsp)
}

// Postcrmv3objectsquotessearchDoSearchWithBodyWithResponse request with arbitrary body returning *Postcrmv3objectsquotessearchDoSearchResponse
func (c *ClientWithResponses) Postcrmv3objectsquotessearchDoSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotessearchDoSearchResponse, error) {
	rsp, err := c.Postcrmv3objectsquotessearchDoSearchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostcrmv3objectsquotessearchDoSearchResponse(rsp)
}

func (c *ClientWithResponses) Postcrmv3objectsquotessearchDoSearchWithResponse(ctx context.Context, body Postcrmv3objectsquotessearchDoSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*Postcrmv3objectsquotessearchDoSearchResponse, error) {
	rsp, err := c.Postcrmv3objectsquotessearchDoSearch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostcrmv3objectsquotessearchDoSearchResponse(rsp)
}

// Getcrmv3objectsquotesQuoteIdGetByIdWithResponse request returning *Getcrmv3objectsquotesQuoteIdGetByIdResponse
func (c *ClientWithResponses) Getcrmv3objectsquotesQuoteIdGetByIdWithResponse(ctx context.Context, quoteId string, params *Getcrmv3objectsquotesQuoteIdGetByIdParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesQuoteIdGetByIdResponse, error) {
	rsp, err := c.Getcrmv3objectsquotesQuoteIdGetById(ctx, quoteId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetcrmv3objectsquotesQuoteIdGetByIdResponse(rsp)
}

// Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllWithResponse request returning *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse
func (c *ClientWithResponses) Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllWithResponse(ctx context.Context, quoteId string, toObjectType string, params *Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllParams, reqEditors ...RequestEditorFn) (*Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse, error) {
	rsp, err := c.Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAll(ctx, quoteId, toObjectType, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse(rsp)
}

// ParseGetcrmv3objectsquotesGetPageResponse parses an HTTP response from a Getcrmv3objectsquotesGetPageWithResponse call
func ParseGetcrmv3objectsquotesGetPageResponse(rsp *http.Response) (*Getcrmv3objectsquotesGetPageResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Getcrmv3objectsquotesGetPageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParsePostcrmv3objectsquotesbatchreadReadResponse parses an HTTP response from a Postcrmv3objectsquotesbatchreadReadWithResponse call
func ParsePostcrmv3objectsquotesbatchreadReadResponse(rsp *http.Response) (*Postcrmv3objectsquotesbatchreadReadResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postcrmv3objectsquotesbatchreadReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BatchResponseSimplePublicObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 207:
		var dest BatchResponseSimplePublicObjectWithErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON207 = &dest

	}

	return response, nil
}

// ParsePostcrmv3objectsquotessearchDoSearchResponse parses an HTTP response from a Postcrmv3objectsquotessearchDoSearchWithResponse call
func ParsePostcrmv3objectsquotessearchDoSearchResponse(rsp *http.Response) (*Postcrmv3objectsquotessearchDoSearchResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postcrmv3objectsquotessearchDoSearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CollectionResponseWithTotalSimplePublicObjectForwardPaging
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseGetcrmv3objectsquotesQuoteIdGetByIdResponse parses an HTTP response from a Getcrmv3objectsquotesQuoteIdGetByIdWithResponse call
func ParseGetcrmv3objectsquotesQuoteIdGetByIdResponse(rsp *http.Response) (*Getcrmv3objectsquotesQuoteIdGetByIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Getcrmv3objectsquotesQuoteIdGetByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SimplePublicObjectWithAssociations
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse parses an HTTP response from a Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllWithResponse call
func ParseGetcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse(rsp *http.Response) (*Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Getcrmv3objectsquotesQuoteIdassociationsToObjectTypeGetAllResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CollectionResponseAssociatedIdForwardPaging
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}
